### ISSUE TITLE
能让他在 windows 上运行吗？

### ISSUE THREAD

**Issue by 456vv** [saltbo/zpan#70]
自行编译，执行后出现 ```panic```
```
zpan server --config zpan.yml

Using config file: zpan.yml
runtime: bad pointer in frame github.com/konsorten/go-windows-terminal-sequences.EnableVirtualTerminalProcessing at 0xc000011690: 0x58
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw(0x2cd9357, 0x1e)
        D:/Go/src/runtime/panic.go:1116 +0x79 fp=0xaf3e3ff2b0 sp=0xaf3e3ff280 pc=0xd7a5b9
runtime.adjustpointers(0xc000011690, 0xaf3e3ff3a0, 0xaf3e3ff728, 0x365beb0, 0x1927b00)
        D:/Go/src/runtime/stack.go:605 +0x1e8 fp=0xaf3e3ff300 sp=0xaf3e3ff2b0 pc=0xd8f6a8
runtime.adjustframe(0xaf3e3ff638, 0xaf3e3ff728, 0x1927b00)
        D:/Go/src/runtime/stack.go:647 +0x36b fp=0xaf3e3ff3d0 sp=0xaf3e3ff300 pc=0xd8fa2b
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000085680, 0x0, 0x0, 0x7fffffff, 0x2ff6b78, 0xaf3e3ff728, 0x0, ...)
        D:/Go/src/runtime/traceback.go:334 +0x11b5 fp=0xaf3e3ff6a0 sp=0xaf3e3ff3d0 pc=0xd9b9d5
runtime.copystack(0xc000085680, 0x4000)
        D:/Go/src/runtime/stack.go:910 +0x2a7 fp=0xaf3e3ff858 sp=0xaf3e3ff6a0 pc=0xd901a7
runtime.newstack()
        D:/Go/src/runtime/stack.go:1076 +0x2a5 fp=0xaf3e3ffa08 sp=0xaf3e3ff858 pc=0xd90585
runtime.morestack()
        D:/Go/src/runtime/asm_amd64.s:449 +0x97 fp=0xaf3e3ffa10 sp=0xaf3e3ffa08 pc=0xdab877

goroutine 51 [copystack]:
runtime.concatstrings(0xc0000113e8, 0xc0000113b8, 0x2, 0x2, 0x0, 0x0)
        D:/Go/src/runtime/string.go:24 +0x2f8 fp=0xc000011370 sp=0xc000011368 pc=0xd91f98
runtime.concatstring2(0xc00046f3e8, 0x2cc1cfe, 0xc, 0x2cb82bb, 0x1, 0x0, 0x0)
        D:/Go/src/runtime/string.go:59 +0x4e fp=0xc0000113b0 sp=0xc000011370 pc=0xd91fee
syscall.UTF16FromString(0x2cc1cfe, 0xc, 0x21c6647a208, 0x0, 0x0, 0x0, 0x0)
        D:/Go/src/syscall/syscall_windows.go:46 +0xcc fp=0xc000011498 sp=0xc0000113b0 pc=0xdffe2c
syscall.UTF16PtrFromString(...)
        D:/Go/src/syscall/syscall_windows.go:96
syscall.LoadDLL(0x2cc1cfe, 0xc, 0x21c6647a208, 0xc00046f608, 0xd4f2d0)
        D:/Go/src/syscall/dll_windows.go:70 +0x54 fp=0xc000011550 sp=0xc000011498 pc=0xdfa494
syscall.(*LazyDLL).Load(0xc000004720, 0x0, 0x0)
        D:/Go/src/syscall/dll_windows.go:245 +0xc8 fp=0xc0000115a0 sp=0xc000011550 pc=0xdfc328
syscall.(*LazyProc).Find(0xc00048bcb0, 0x0, 0x0)
        D:/Go/src/syscall/dll_windows.go:300 +0xbf fp=0xc0000115f8 sp=0xc0000115a0 pc=0xdfc63f
syscall.(*LazyProc).mustFind(...)
        D:/Go/src/syscall/dll_windows.go:318
syscall.(*LazyProc).Call(0xc00048bcb0, 0xc00034e030, 0x2, 0x2, 0xc00046f6c8, 0xe083b7, 0x7ff8e62a2a90, 0x2)
        D:/Go/src/syscall/dll_windows.go:336 +0x36 fp=0xc000011648 sp=0xc0000115f8 pc=0xdfc856
github.com/konsorten/go-windows-terminal-sequences.EnableVirtualTerminalProcessing(0x58, 0x1, 0xc00008b1d0, 0xc00046f6fc)
        K:/code/GO/pkg/mod/github.com/konsorten/go-windows-terminal-sequences@v1.0.1/sequences.go:30 +0xcb fp=0xc0000116a8 sp=0xc000011648 pc=0x154632b
github.com/sirupsen/logrus.initTerminal(0x3169c00, 0xc0000cc010)
        K:/code/GO/pkg/mod/github.com/sirupsen/logrus@v1.4.2/terminal_check_windows.go:16 +0x65 fp=0xc0000116d8 sp=0xc0000116a8 pc=0x154c665
github.com/sirupsen/logrus.checkIfTerminal(0x3169c00, 0xc0000cc010, 0xc000059000)
        K:/code/GO/pkg/mod/github.com/sirupsen/logrus@v1.4.2/terminal_check_windows.go:31 +0xae fp=0xc000011710 sp=0xc0000116d8 pc=0x154c72e
github.com/sirupsen/logrus.(*TextFormatter).init(...)
        K:/code/GO/pkg/mod/github.com/sirupsen/logrus@v1.4.2/text_formatter.go:86
github.com/sirupsen/logrus.(*TextFormatter).Format.func1()
        K:/code/GO/pkg/mod/github.com/sirupsen/logrus@v1.4.2/text_formatter.go:170 +0x58 fp=0xc000011740 sp=0xc000011710 pc=0x154ff78
sync.(*Once).doSlow(0xc0004d1670, 0xc00046f968)
        D:/Go/src/sync/once.go:66 +0xf7 fp=0xc000011790 sp=0xc000011740 pc=0xdc7ab7
sync.(*Once).Do(...)
        D:/Go/src/sync/once.go:57
github.com/sirupsen/logrus.(*TextFormatter).Format(0xc0004d1630, 0xc0006c4070, 0xc00046fd40, 0x154fe14, 0x2bec1e0, 0xc0006c2030, 0xc00046fd88)
        K:/code/GO/pkg/mod/github.com/sirupsen/logrus@v1.4.2/text_formatter.go:170 +0xf78 fp=0xc000011d10 sp=0xc000011790 pc=0x154d878
github.com/sirupsen/logrus.(*Entry).write(0xc0006c4070)
        K:/code/GO/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:255 +0x83 fp=0xc000011d98 sp=0xc000011d10 pc=0x1547ca3
github.com/sirupsen/logrus.Entry.log(0xc0004b3110, 0xc0006c2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        K:/code/GO/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:231 +0x1af fp=0xc000011e10 sp=0xc000011d98 pc=0x154790f
github.com/sirupsen/logrus.(*Entry).Log(0xc0006c4000, 0xc000000003, 0xc00046ff98, 0x1, 0x1)
        K:/code/GO/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xf2 fp=0xc000011f18 sp=0xc000011e10 pc=0x1547f32
github.com/sirupsen/logrus.(*Logger).Log(0xc0004b3110, 0x3, 0xc00046ff98, 0x1, 0x1)
        K:/code/GO/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 +0x85 fp=0xc000011f58 sp=0xc000011f18 pc=0x154ae45
github.com/sirupsen/logrus.(*Logger).Warn(...)
        K:/code/GO/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:216
github.com/sirupsen/logrus.(*Logger).Warning(...)
        K:/code/GO/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:220
github.com/storyicon/grbac.(*Controller).runCronTab(0xc0004b3180)
        K:/code/GO/pkg/mod/github.com/storyicon/grbac@v0.0.0-20200224041032-a0461737df7e/grbac.go:197 +0x205 fp=0xc000011fd8 sp=0xc000011f58 pc=0x15cfd85
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000011fe0 sp=0xc000011fd8 pc=0xdad541
created by github.com/storyicon/grbac.New
        K:/code/GO/pkg/mod/github.com/storyicon/grbac@v0.0.0-20200224041032-a0461737df7e/grbac.go:140 +0x273

goroutine 1 [runnable]:
compress/flate.(*decompressor).huffSym(0xc0004f5300, 0xc0004f5328, 0x5, 0x0, 0x0)
        D:/Go/src/compress/flate/inflate.go:707 +0x273 fp=0xc0006c1428 sp=0xc0006c1420 pc=0x10536f3
compress/flate.(*decompressor).huffmanBlock(0xc0004f5300)
        D:/Go/src/compress/flate/inflate.go:494 +0xd5 fp=0xc0006c14b0 sp=0xc0006c1428 pc=0x1052215
compress/flate.(*decompressor).nextBlock(0xc0004f5300)
        D:/Go/src/compress/flate/inflate.go:327 +0x17d fp=0xc0006c14d8 sp=0xc0006c14b0 pc=0x10515dd
compress/flate.(*decompressor).Read(0xc0004f5300, 0xc0004b4e00, 0x200, 0x200, 0x200, 0x21c41011500, 0xc0004b4e00)
        D:/Go/src/compress/flate/inflate.go:347 +0x7e fp=0xc0006c1510 sp=0xc0006c14d8 pc=0x10516fe
archive/zip.(*pooledFlateReader).Read(0xc0003a3400, 0xc0004b4e00, 0x200, 0x200, 0x0, 0x0, 0x0)
        D:/Go/src/archive/zip/register.go:90 +0xb3 fp=0xc0006c1570 sp=0xc0006c1510 pc=0x15d43f3
archive/zip.(*checksumReader).Read(0xc0004d1810, 0xc0004b4e00, 0x200, 0x200, 0xc0004b4e00, 0x0, 0x0)
        D:/Go/src/archive/zip/reader.go:194 +0x73 fp=0xc0006c15e0 sp=0xc0006c1570 pc=0x15d1393
bytes.(*Buffer).ReadFrom(0xc0006c1688, 0x21c66601118, 0xc0004d1810, 0x21c66601118, 0x3169620, 0x47)
        D:/Go/src/bytes/buffer.go:204 +0xbb fp=0xc0006c1650 sp=0xc0006c15e0 pc=0xe5d67b
io/ioutil.readAll(0x21c66601118, 0xc0004d1810, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        D:/Go/src/io/ioutil/ioutil.go:36 +0xea fp=0xc0006c16d0 sp=0xc0006c1650 pc=0xee9c0a
io/ioutil.ReadAll(...)
        D:/Go/src/io/ioutil/ioutil.go:45
github.com/rakyll/statik/fs.unzip(0xc0004c3080, 0x0, 0x0, 0x0, 0x0, 0x0)
        K:/code/GO/pkg/mod/github.com/rakyll/statik@v0.1.7/fs/fs.go:237 +0xf1 fp=0xc0006c1738 sp=0xc0006c16d0 pc=0x15d7851
github.com/rakyll/statik/fs.NewWithNamespace(0x2cba859, 0x5, 0x1, 0xc0006c1a00, 0xc0006c1a10, 0x15efea8)
        K:/code/GO/pkg/mod/github.com/rakyll/statik@v0.1.7/fs/fs.go:91 +0x245 fp=0xc0006c1978 sp=0xc0006c1738 pc=0x15d6305
github.com/saltbo/moreu/assets.EmbedFS(0xc0004bc700, 0xc00028b23a)
        K:/code/GO/pkg/mod/github.com/saltbo/moreu@v0.0.0-20201014155738-fd9467a0d74b/assets/fs.go:12 +0x45 fp=0xc0006c19d8 sp=0xc0006c1978 pc=0x15d8785
github.com/saltbo/moreu/moreu.(*Engine).SetupEmbedStatic(0xc000342740)
        K:/code/GO/pkg/mod/github.com/saltbo/moreu@v0.0.0-20201014155738-fd9467a0d74b/moreu/moreu.go:54 +0x29 fp=0xc0006c1a20 sp=0xc0006c19d8 pc=0x15eff69
github.com/saltbo/zpan/cmd.serverRun(0xc0004c0000)
        K:/code/GO/pkg/mod/github.com/saltbo/zpan@v1.4.1/cmd/server.go:73 +0x23e fp=0xc0006c1d50 sp=0xc0006c1a20 pc=0x185a7be
github.com/saltbo/zpan/cmd.glob..func1(0x2a826c0, 0xc000098620, 0x0, 0x2)
        K:/code/GO/pkg/mod/github.com/saltbo/zpan@v1.4.1/cmd/server.go:50 +0x2e fp=0xc0006c1d68 sp=0xc0006c1d50 pc=0x185b9ce
github.com/spf13/cobra.(*Command).execute(0x2a826c0, 0xc000098600, 0x2, 0x2, 0x2a826c0, 0xc000098600)
        K:/code/GO/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2 fp=0xc0006c1e40 sp=0xc0006c1d68 pc=0xf213e2
github.com/spf13/cobra.(*Command).ExecuteC(0x2a82420, 0xd89878, 0x1922d60, 0xc00004e000)
        K:/code/GO/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375 fp=0xc0006c1f18 sp=0xc0006c1e40 pc=0xf22115
github.com/spf13/cobra.(*Command).Execute(...)
        K:/code/GO/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/saltbo/zpan/cmd.Execute()
        K:/code/GO/pkg/mod/github.com/saltbo/zpan@v1.4.1/cmd/root.go:48 +0x38 fp=0xc0006c1f78 sp=0xc0006c1f18 pc=0x185a0b8
main.main()
        K:/code/GO/pkg/mod/github.com/saltbo/zpan@v1.4.1/main.go:27 +0x27 fp=0xc0006c1f88 sp=0xc0006c1f78 pc=0x185c027
runtime.main()
        D:/Go/src/runtime/proc.go:204 +0x209 fp=0xc0006c1fe0 sp=0xc0006c1f88 pc=0xd7cd69
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0006c1fe8 sp=0xc0006c1fe0 pc=0xdad541

goroutine 2 [force gc (idle)]:
runtime.gopark(0x2ff6e08, 0x37f5e80, 0x1411, 0x1)
        D:/Go/src/runtime/proc.go:306 +0xfa fp=0xc000051fb0 sp=0xc000051f90 pc=0xd7d13a
runtime.goparkunlock(...)
        D:/Go/src/runtime/proc.go:312
runtime.forcegchelper()
        D:/Go/src/runtime/proc.go:255 +0xcd fp=0xc000051fe0 sp=0xc000051fb0 pc=0xd7cfcd
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000051fe8 sp=0xc000051fe0 pc=0xdad541
created by runtime.init.6
        D:/Go/src/runtime/proc.go:243 +0x3c

goroutine 3 [GC sweep wait]:
runtime.gopark(0x2ff6e08, 0x37f6040, 0x140c, 0x1)
        D:/Go/src/runtime/proc.go:306 +0xfa fp=0xc000053fa8 sp=0xc000053f88 pc=0xd7d13a
runtime.goparkunlock(...)
        D:/Go/src/runtime/proc.go:312
runtime.bgsweep(0xc0000300e0)
        D:/Go/src/runtime/mgcsweep.go:182 +0x149 fp=0xc000053fd8 sp=0xc000053fa8 pc=0xd66b49
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000053fe0 sp=0xc000053fd8 pc=0xdad541
created by runtime.gcenable
        D:/Go/src/runtime/mgc.go:217 +0x67

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x2ff6e08, 0x37f6760, 0x140d, 0x1)
        D:/Go/src/runtime/proc.go:306 +0xfa fp=0xc000061f78 sp=0xc000061f58 pc=0xd7d13a
runtime.goparkunlock(...)
        D:/Go/src/runtime/proc.go:312
runtime.bgscavenge(0xc0000300e0)
        D:/Go/src/runtime/mgcscavenge.go:314 +0x2b9 fp=0xc000061fd8 sp=0xc000061f78 pc=0xd64c59
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000061fe0 sp=0xc000061fd8 pc=0xdad541
created by runtime.gcenable
        D:/Go/src/runtime/mgc.go:218 +0x89

goroutine 18 [finalizer wait]:
runtime.gopark(0x2ff6e08, 0x382ae08, 0x1ffff1410, 0x1)
        D:/Go/src/runtime/proc.go:306 +0xfa fp=0xc000055f58 sp=0xc000055f38 pc=0xd7d13a
runtime.goparkunlock(...)
        D:/Go/src/runtime/proc.go:312
runtime.runfinq()
        D:/Go/src/runtime/mfinal.go:175 +0xb2 fp=0xc000055fe0 sp=0xc000055f58 pc=0xd5b612
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000055fe8 sp=0xc000055fe0 pc=0xdad541
created by runtime.createfing
        D:/Go/src/runtime/mfinal.go:156 +0x68

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x2ff6c88, 0xc00044c690, 0xd41418, 0x0)
        D:/Go/src/runtime/proc.go:306 +0xfa fp=0xc00005df60 sp=0xc00005df40 pc=0xd7d13a
runtime.gcBgMarkWorker(0xc00003a000)
        D:/Go/src/runtime/mgc.go:1891 +0x114 fp=0xc00005dfd8 sp=0xc00005df60 pc=0xd5f394
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00005dfe0 sp=0xc00005dfd8 pc=0xdad541
created by runtime.gcBgMarkStartWorkers
        D:/Go/src/runtime/mgc.go:1839 +0x7e

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x2ff6c88, 0xc00044c6a0, 0x1418, 0x0)
        D:/Go/src/runtime/proc.go:306 +0xfa fp=0xc000465f60 sp=0xc000465f40 pc=0xd7d13a
runtime.gcBgMarkWorker(0xc00003c800)
        D:/Go/src/runtime/mgc.go:1891 +0x114 fp=0xc000465fd8 sp=0xc000465f60 pc=0xd5f394
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000465fe0 sp=0xc000465fd8 pc=0xdad541
created by runtime.gcBgMarkStartWorkers
        D:/Go/src/runtime/mgc.go:1839 +0x7e

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x2ff6c88, 0xc00002a0a0, 0x1418, 0x0)
        D:/Go/src/runtime/proc.go:306 +0xfa fp=0xc000467f60 sp=0xc000467f40 pc=0xd7d13a
runtime.gcBgMarkWorker(0xc00003f000)
        D:/Go/src/runtime/mgc.go:1891 +0x114 fp=0xc000467fd8 sp=0xc000467f60 pc=0xd5f394
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000467fe0 sp=0xc000467fd8 pc=0xdad541
created by runtime.gcBgMarkStartWorkers
        D:/Go/src/runtime/mgc.go:1839 +0x7e

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x2ff6c88, 0xc00002a0b0, 0x1418, 0x0)
        D:/Go/src/runtime/proc.go:306 +0xfa fp=0xc00005ff60 sp=0xc00005ff40 pc=0xd7d13a
runtime.gcBgMarkWorker(0xc000041800)
        D:/Go/src/runtime/mgc.go:1891 +0x114 fp=0xc00005ffd8 sp=0xc00005ff60 pc=0xd5f394
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00005ffe0 sp=0xc00005ffd8 pc=0xdad541
created by runtime.gcBgMarkStartWorkers
        D:/Go/src/runtime/mgc.go:1839 +0x7e

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x2ff6c88, 0xc00044c6b0, 0x1418, 0x0)
        D:/Go/src/runtime/proc.go:306 +0xfa fp=0xc000461f60 sp=0xc000461f40 pc=0xd7d13a
runtime.gcBgMarkWorker(0xc000044000)
        D:/Go/src/runtime/mgc.go:1891 +0x114 fp=0xc000461fd8 sp=0xc000461f60 pc=0xd5f394
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000461fe0 sp=0xc000461fd8 pc=0xdad541
created by runtime.gcBgMarkStartWorkers
        D:/Go/src/runtime/mgc.go:1839 +0x7e

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x2ff6c88, 0xc00044c6c0, 0x1418, 0x0)
        D:/Go/src/runtime/proc.go:306 +0xfa fp=0xc000063f60 sp=0xc000063f40 pc=0xd7d13a
runtime.gcBgMarkWorker(0xc000046800)
        D:/Go/src/runtime/mgc.go:1891 +0x114 fp=0xc000063fd8 sp=0xc000063f60 pc=0xd5f394
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000063fe0 sp=0xc000063fd8 pc=0xdad541
created by runtime.gcBgMarkStartWorkers
        D:/Go/src/runtime/mgc.go:1839 +0x7e

goroutine 38 [GC worker (idle)]:
runtime.gopark(0x2ff6c88, 0xc00044c6d0, 0x1418, 0x0)
        D:/Go/src/runtime/proc.go:306 +0xfa fp=0xc000463f60 sp=0xc000463f40 pc=0xd7d13a
runtime.gcBgMarkWorker(0xc000049000)
        D:/Go/src/runtime/mgc.go:1891 +0x114 fp=0xc000463fd8 sp=0xc000463f60 pc=0xd5f394
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000463fe0 sp=0xc000463fd8 pc=0xdad541
created by runtime.gcBgMarkStartWorkers
        D:/Go/src/runtime/mgc.go:1839 +0x7e

goroutine 39 [GC worker (idle)]:
runtime.gopark(0x2ff6c88, 0xc0002527b0, 0x1418, 0x0)
        D:/Go/src/runtime/proc.go:306 +0xfa fp=0xc00046df60 sp=0xc00046df40 pc=0xd7d13a
runtime.gcBgMarkWorker(0xc00004b800)
        D:/Go/src/runtime/mgc.go:1891 +0x114 fp=0xc00046dfd8 sp=0xc00046df60 pc=0xd5f394
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00046dfe0 sp=0xc00046dfd8 pc=0xdad541
created by runtime.gcBgMarkStartWorkers
        D:/Go/src/runtime/mgc.go:1839 +0x7e

goroutine 50 [select]:
runtime.gopark(0x2ff6e58, 0x0, 0x1809, 0x1)
        D:/Go/src/runtime/proc.go:306 +0xfa fp=0xc000469e10 sp=0xc000469df0 pc=0xd7d13a
runtime.selectgo(0xc000469f68, 0xc000469f60, 0x2, 0x0, 0x0)
        D:/Go/src/runtime/select.go:338 +0xd0f fp=0xc000469f38 sp=0xc000469e10 pc=0xd8b70f
database/sql.(*DB).connectionOpener(0xc0004a4410, 0x3182d40, 0xc0004bc0c0)
        D:/Go/src/database/sql/sql.go:1126 +0xf5 fp=0xc000469fc8 sp=0xc000469f38 pc=0x14415f5
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000469fd0 sp=0xc000469fc8 pc=0xdad541
created by database/sql.OpenDB
        D:/Go/src/database/sql/sql.go:740 +0x132
```

**Comment by saltbo** [comment]
后面有时间了会支持的

**Comment by 456vv** [comment]
能不能给我编译一个linux arm6-7 构架的，我尝试使用msys64编译失败。

**Comment by saltbo** [comment]
已移除cgo依赖 关闭cgo即可编译

**Comment by saltbo** [comment]
> 能不能给我编译一个linux arm6-7 构架的，我尝试使用msys64编译失败。

从1.7版本开始增加了 armv6 和 armv7 的制品
